version: '3.7'
services:
  app1:
    
    image: popadukdv/basic_metrics
    #networks:
      #net:
          #ipv4_address: 172.20.1.11
    ports:
      - "8001:80"
    
  app2:
    
    image: popadukdv/basic_metrics
    #networks:
      #net:
          #ipv4_address: 172.20.1.12
    ports:
      - "8002:80"
  web_server:
    
    build: .
    #networks:
      #net:
        #ipv4_address: 172.20.1.10
    ports:
      - "8010:81"
      - "8020:82"
    depends_on:
      - app1
      - app2
#networks:
  #net:
    #driver: bridge
    #ipam: 
      #driver: default
      #config:
      #- subnet: 172.20.1.0/24
      #  gateway: 172.20.1.1