name: Docker Publish Image CI


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-container:

    name: Build container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Login to Docker hub
      - uses: docker/login-action@v1
      - name: Login to Docker Hub
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          pull_request: true
          tags: popadukdv/basic_metrics:latest, popadukdv/basic_metrics:${{ github.run.number }}
          